### ISSUE TITLE
[Build issue]

### ISSUE THREAD

**Issue by tallero** [fabiocolacio/Marker#236]
I get this when trying ninja install

```
[0/1] Installing files.
Installing subdir /home/user/Projects/Marker/data/styles to /usr/share/com.github.fabiocolacio.marker/styles
Installing subdir /home/user/Projects/Marker/data/common to /usr/share/com.github.fabiocolacio.marker/common
Installing subdir /home/user/Projects/Marker/data/scripts to /usr/share/com.github.fabiocolacio.marker/scripts
Installing subdir /home/user/Projects/Marker/data/icons to /usr/share/com.github.fabiocolacio.marker/icons
Installing libscroll-extension.so to /usr/share/com.github.fabiocolacio.marker/extensions
Installing marker to /usr/bin
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.48.0', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 392, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 308, in run
    return minstall.run(remaining_args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 521, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 349, in do_install
    self.install_data(d)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 375, in install_data
    self.do_copyfile(fullfilename, outfilename)
  File "/usr/lib/python3.7/site-packages/mesonbuild/minstall.py", line 234, in do_copyfile
    '{!r}'.format(from_file))
RuntimeError: Tried to install something that isn't a file:'/home/user/Projects/Marker/data/com.github.fabiocolacio.marker.svg'
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by fabiocolacio** [comment]
Hi @tallero,

I have been unable to reproduce this error.

Did you run the commands exactly as shown in the ``README.md``? Did you make sure to run ``ninja install`` with ``sudo``?

What operating system are you using?

**Comment by tallero** [comment]
I used root directly after user compiling, but should be the same I guess.

Il October 7, 2018 7:14:11 PM UTC, Fabio Colacio <notifications@github.com> ha scritto:
>Hi @tallero,
>
>I have been unable to reproduce this error.
>
>Did you run the commands exactly as shown in the ``README.md``? Did you
>make sure to run ``ninja install`` with ``sudo``?
>
>What operating system are you using?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fabiocolacio/Marker/issues/236#issuecomment-427678792

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
