### ISSUE TITLE
FAILED: meson-install: No such file or directory: '_build/help/uk/uk.page'

### ISSUE THREAD

**Issue by rekaerst** [fabiocolacio/Marker#351]
Hello
Running "meson install" fail after commit 93bc98e1.

related build log
```
Running custom install script '/usr/bin/meson --internal yelphelper install --subdir=help --id=Marker --installdir=share/help --sources=index.page@@introduction.page@@pictures.page@@complex-data.page@@settings.page@@legal.xml --symlinks=true --media=figures/icon.png@@figures/scrot.png@@figures/scrot1.png@@figures/scrot2.png@@figures/sketcher.png'
msgfmt: error while opening "/home/arthur/tmp/Marker/help/uk/uk.po" for reading: No such file or directory
Error: cannot open mo file /home/arthur/tmp/Marker/_build/help/uk/uk.gmo
Installing /home/arthur/tmp/Marker/_build/help/uk/index.page to /home/arthur/tmp/Marker/debian/marker/usr/share/help/uk/Marker/index.page
Traceback (most recent call last):
  File "/usr/bin/meson", line 20, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 240, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 229, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 177, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/yelphelper.py", line 131, in run
    install_help(src_subdir, build_subdir, sources, media, langs, install_dir,
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/yelphelper.py", line 72, in install_help
    shutil.copy2(infile, outfile)
  File "/usr/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/arthur/tmp/Marker/_build/help/uk/index.page'
FAILED: install script '/usr/bin/meson --internal yelphelper install --subdir=help --id=Marker --installdir=share/help --sources=index.page@@introduction.page@@pictures.page@@complex-data.page@@settings.page@@legal.xml --symlinks=true --media=figures/icon.png@@figures/scrot.png@@figures/scrot1.png@@figures/scrot2.png@@figures/sketcher.png' exit code 1, stopped
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:7: install] Error 1

```

**Comment by apandada1** [comment]
@unavaliabl3 This should be fixed now. Can you check?
